geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
]     

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.urls import path
from django.contrib import admin
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

if settings.DEBUG:
    import debug_toolbar


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', admin.site.urls),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('social/', include('social_django.urls', namespace='social')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/basketapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Product


class Basket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='basket')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)
    add_datetime = models.DateTimeField(verbose_name='время', auto_now_add=True)

    @property
    def product_cost(self):
        "return cost of all products this type"
        return self.product.price * self.quantity

    @property
    def total_quantity(self):
        "return total quantity for user"
        _items = Basket.objects.select_related('product').filter(user=self.user)
        _totalquantity = sum(list(map(lambda x: x.quantity, _items)))
        return _totalquantity

    @property
    def total_cost(self):
        "return total cost for user"
        #_items = Basket.objects.filter(user=self.user)
        _items = Basket.objects.select_related('product').filter(user=self.user)
        _totalcost = sum(list(map(lambda x: x.product_cost, _items)))
        return _totalcost

geekshop/basketapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.urls import reverse
from basketapp.models import Basket
from mainapp.models import Product
import json

main_links_menu = [
        {'href': 'main', 'name': 'Главная'},
        {'href': 'products:index', 'name': 'Продукты'},
        {'href': 'contact', 'name': 'Контакты'}
    ]


def get_basket_sum(request):
    basket = request.user.basket.all()
    total = 0
    for product in basket:
        position = get_object_or_404(Product, pk=product.pk)
        total = total + position.price * product.quantity
    return total


@login_required
def basket(request):
    title = 'Корзина'
    basket_items = Basket.objects.filter(user=request.user).order_by('product__category')
    content = {
        'title': title,
        'basket_items': basket_items,
        'links_menu': main_links_menu,
    }
    return render(request, 'basketapp/basket.html', content)


@login_required
def basket_add(request, pk):
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('products:product', args=[pk]))
    product = get_object_or_404(Product, pk=pk)
    basket = Basket.objects.filter(user=request.user, product=product).first()

    if not basket:
        basket = Basket(user=request.user, product=product)

    basket.quantity += 1
    basket.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, pk):
    basket_record = get_object_or_404(Basket, pk=pk)
    basket_record.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_edit(request, pk, quantity):
    if request.is_ajax():
        quantity = int(quantity)
        new_basket_item = Basket.objects.get(pk=int(pk))
        if quantity > 0:
            new_basket_item.quantity = quantity
            new_basket_item.save()
        else:
            new_basket_item.delete()
        basket_items = Basket.objects.filter(user=request.user).order_by('product__category')
        content = {
            'basket_items': basket_items,
        }
        result = render_to_string('basketapp/includes/inc_basket_list.html', content)        
        return JsonResponse({'result': result})

geekshop/basketapp/templates/basketapp/includes/inc_basket_list.html
{% for item in basket_items %}
    <div class="basket_record">
        <img src="/media/{{ item.product.image }}" 
             alt="{{ item.product.short_desc }}" width="70">
        <span class="category_name">{{ item.product.category.name }}</span> 
        <span class="product_name">{{ item.product.name }}</span>
        <span class="product_price">{{ item.product.price }}&nbspруб</span>
        <input type="number" name="{{ item.pk }}" min="0" 
                            value="{{ item.quantity }}"
                            class="input-form-basket">
        <span class="product_cost">{{ item.cost }}&nbspруб</span>
        <button class="btn btn-round">
            <a href="{% url 'basket:remove' item.pk %}" class="">
                удалить
            </a>
        </button>
    </div>
{% endfor %}

{% if basket_items %}
    <div class="basket_summary">
        В корзине {{ basket_items.0.total_quantity }} товаров общей стоимостью
        {{ basket_items.0.total_cost }} руб
    </div>
{% endif %}

geekshop/basketapp/templates/basketapp/includes/inc_menu.html
{% load staticfiles %}
<div class="header">
    <a href="{% url 'main' %}"><img src="{% static 'img/logotip.png' %}" alt="logo" class="logotip"></a>
    <ul class="main-menu">
        {% for link in links_menu %}
            <li class="menu-list"><a
                    class="menu-link {% if request.resolver_match.view_name == link.href %}menu-link-active {% endif %}"
                                     href="{% url link.href %}">{{ link.name }}</a></li>
        {% endfor %}
        {% if user.is_authenticated %}
        <li class="menu-list">
            <a href="{% url 'auth:edit' %}" class="menu-link">
                {{ user.first_name|default:'Пользователь' }}          
            </a>
        </li>
        {% endif %}  
        <li class="menu-list">
            {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}" class="menu-link">выйти</a>
            {% else %}
            <a href="{% url 'auth:login' %}" class="menu-link">войти</a>
            или
            <a href="{% url 'auth:register' %}" class="menu-link">Зарегистрироваться</a>
            {% endif %}
        </li>
    </ul>
    <a href="#" class="search"></a>
    <a href="{% url 'basket:view' %}" class="basket">
        <span>
            {% if basket %} {{ basket|length }} {% endif %}
        </span>
    </a>
</div>