geekshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.ProductCategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductView.as_view(), name='products'),
#    path('products/read/<int:pk>/', adminapp.ProductListView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
]     

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.urls import path
from django.contrib import admin
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

if settings.DEBUG:
    import debug_toolbar


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', admin.site.urls),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('social/', include('social_django.urls', namespace='social')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   path('', mainapp.products, name='index'),
   path('category/<int:pk>/', mainapp.products, name='category'),
   path('product/<int:pk>/', mainapp.product, name='product'),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='Описание', blank=True)
    image = models.ImageField(upload_to='category_images', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

geekshop/mainapp/views.py
from django.shortcuts import render
from .models import ProductCategory, Product
from django.shortcuts import get_object_or_404
from basketapp.models import Basket
import random


main_links_menu = [
        {'href': 'main', 'name': 'Главная'},
        {'href': 'products:index', 'name': 'Продукты'},
        {'href': 'contact', 'name': 'Контакты'}
    ]


def get_basket_sum(request):
    basket = []
    if request.user.is_authenticated:
        basket = request.user.basket.all()
    total = 0
    for product in basket:
        position = get_object_or_404(Product, pk=product.pk)
        total = total + position.price * product.quantity
    return total


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]

    
def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).\
                                    exclude(pk=hot_product.pk)[:3]

    return same_products

def main(request):
    title = 'Главная'
    basket = []
    if request.user.is_authenticated:
        basket = request.user.basket.all()
    content = {
            'title': title,
            'links_menu': main_links_menu,
            'basket': basket            
        }
    return render(request, 'mainapp/index.html', content)


def products(request, pk=None):
    title = 'Категории'
    categories = ProductCategory.objects.all()
    basket = []
    if request.user.is_authenticated:
        basket = request.user.basket.all()
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by('price')
            category = {'name': 'Все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')
        content = {
            'title': title,
            'links_menu': main_links_menu,
            'category': category,
            'products': products,
            'categories': categories,
            'basket': basket,
            'same_products': same_products,
            'hot_product': hot_product,
        }
        return render(request, 'mainapp/products.html', content)
    content = {
        'title': title, 
        'links_menu': main_links_menu, 
        'same_products': same_products,
        'categories': categories,
        'basket': basket,
        'same_products': same_products,
        'hot_product': hot_product,
    }
    print(categories)
    return render(request, 'mainapp/catalog.html', content)


def contact(request):
    title = 'Контакты'
    basket = []
    if request.user.is_authenticated:
        basket = request.user.basket.all()
    content = {
            'title': title,
            'links_menu': main_links_menu,
            'basket': basket
        }
    return render(request, 'mainapp/contacts.html', content)

def product(request, pk):
    title = 'продукты'
    content = {
        'title': title,
        'links_menu': main_links_menu,
        'product_links_menu': ProductCategory.objects.all(), 
        'product': get_object_or_404(Product, pk=pk), 
        'basket': get_basket(request.user),
    }
    
    return render(request, 'mainapp/product.html', content)

geekshop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
  <li>
    <a href="{% url 'products:category' 0 %}" 
       class="{% if request.resolver_match.kwargs.pk == 0 %}
                menu-link-active
              {% endif %}">
      Все
    </a>
  </li>
  {% for category in categories %}
    <li>
      <a href="{% url 'products:category' category.pk %}" 
         class="{% if request.resolver_match.kwargs.pk|add:'0' == category.pk %}
                  menu-link-active
                {% endif %}">
        {{ category.name }}
      </a>
    </li>
  {% endfor %}
</ul>

geekshop/mainapp/templates/mainapp/includes/inc_menu.html
{% load staticfiles %}
{% load custom_tags %}
<div class="header">
    <a href="{% url 'main' %}"><img src="{% static 'img/logotip.png' %}" alt="logo" class="logotip"></a>
    <ul class="main-menu">
        {% for link in links_menu %}
            <li class="menu-list"><a
                    class="menu-link {% if request.resolver_match.view_name == link.href %}menu-link-active {% endif %}"
                                     href="{% url link.href %}">{{ link.name }}</a></li>
        {% endfor %}
        {% if user.is_authenticated %}
        <li class="menu-list">
            <a href="{% url 'auth:edit' %}" class="menu-link">
                {{ user.first_name|default:'Пользователь' }}          
            </a>
        </li>
        {% endif %} 
        {% if user.is_superuser %}
            <li class="menu-list">
            <a href="{% url 'admin_custom:users' %}">админка</a>
            </li>
        {% endif %} 
        <li class="menu-list">
            {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}" class="menu-link">выйти</a>
            {% else %}
            <a href="{% url 'auth:login' %}" class="menu-link">войти</a>
            или
            <a href="{% url 'auth:register' %}" class="menu-link">Зарегистрироваться</a>
            {% endif %}
            {% if basket %}
            <a href="{% url 'basket:view' %}" class="menu-link">
                {{ request.user|basket_total_cost }} руб 
                ({{ request.user|total_quantity }} шт)
            </a>
            {% endif %}
        </li>
    </ul>
</div>