geekshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.ProductCategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductView.as_view(), name='products'),
#    path('products/read/<int:pk>/', adminapp.ProductListView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
]     

geekshop/geekshop/urls.py
from django.urls import path
from django.contrib import admin
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

if settings.DEBUG:
    import debug_toolbar


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', admin.site.urls),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('social/', include('social_django.urls', namespace='social')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/views.py
from django.shortcuts import render

# Create your views here.
from authapp.models import ShopUser
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect
from django.urls import reverse_lazy
from mainapp.models import Product, ProductCategory
from django.contrib.auth.decorators import user_passes_test
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator


class ProductCategoryListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категории'
        return context



class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    fields = '__all__'
    success_url = reverse_lazy('adminapp:categories')
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категории'
        context['title_submenu'] = 'Создание категории'
        return context



class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    fields = '__all__'
    success_url = reverse_lazy('adminapp:categories')
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категории'
        context['title_submenu'] = 'Изменение категории'
        return context


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('adminapp:categories')
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категории'
        context['title_submenu'] = 'Удаление категории'
        return context


class ProductView(ListView):
    model = Product
    template_name = 'adminapp/products.html'
    #queryset = Product.objects.filter(category__pk=kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Продукты'
        if self.kwargs['pk'] == 0:
            category = {'pk': 0}
        else:
            category = get_object_or_404(ProductCategory, pk=self.kwargs['pk'])
        context['category'] = category
        return context

    def get_queryset(self):
        if self.kwargs['pk'] == 0:
            return Product.objects.all()
        return Product.objects.filter(category__pk=self.kwargs['pk'])

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ProductListView(ListView):
    model = Product
    template_name = 'adminapp/products.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ProductCreateView(CreateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    fields = '__all__'
    #success_url = reverse_lazy('adminapp:products')
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Продукты'
        context['title_submenu'] = 'Создание товара'
        #category = get_object_or_404(ProductCategory, pk=self.kwargs['pk'])
        context['pk'] = self.kwargs['pk']
        return context
    
    def get_success_url(self):
        return reverse_lazy('adminapp:products',  kwargs={'pk': self.kwargs['pk']})


class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    fields = '__all__'
    success_url = reverse_lazy('adminapp:products')
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('adminapp:products',  kwargs={'pk': 0})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Продукты'
        context['title_submenu'] = 'Редактирование товара'
        category = {'pk': 0}
        context['category'] = category
        return context


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'adminapp/product_update.html'
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('adminapp:products',  kwargs={'pk': 0})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Продукты'
        context['title_submenu'] = 'Удаление товара'
        category = {'pk': 0}
        context['category'] = category
        return context


class UserListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Пользователи'
        return context


class UserCreateView(CreateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    fields = '__all__'
    success_url = reverse_lazy('adminapp:users')
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Пользователи'
        context['title_submenu'] = 'Создание пользователя'
        return context


class UserUpdateView(UpdateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    fields = '__all__'
    success_url = reverse_lazy('adminapp:users')
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Пользователи'
        context['title_submenu'] = 'Обновление пользователя'
        return context

class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('adminapp:users')
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Пользователи'
        context['title_submenu'] = 'Удаление пользователя'
        return context

    def delete(self, request, *args, **kwargs):
        user = get_object_or_404(ShopUser, pk=kwargs['pk'])
        user.is_active = False
        user.save()
        return HttpResponseRedirect(self.success_url)    

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% endblock %}

    {% block js %}
        <script src="{% static 'js/jquery-3.4.0.min.js' %}"></script>
        <script src="{% static 'js/basket_scripts.js' %}"></script>
    {% endblock %}
</head>
<body>
  <div class="admin_container">        
    <div class="h2 text-center head">
      {{ title }}
    </div>
    {% block menu %}
      <div class="admin_menu">
        {% include 'adminapp/includes/inc_menu.html' %}
      </div>
    {% endblock %}
           
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="categories_list">
    <button class="new_category">
      <a href={% url 'admin_custom:category_create' %}>
        новая категория
      </a>
    </button>
    <div class="row mt-5"> 
    {% for object in object_list %}

      <div class="card mx-2 mb-3" style="max-width: 540px">
        <div class="row no-gutters">
          <div class="col-md-4 ">
            <img src="/media/{{object.image|default:'products_images/default.jpg'}}" class="card-img" alt="{{ object.name }}">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{ object.name|title }}</h5>
              <p class="card-text">{{ object.description|title }}</p>
              {% comment %} <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> {% endcomment %}
              <a class="btn btn-primary" href="{% url 'admin_custom:products' object.pk %}" role="button">Товары категории</a>
              <a class="btn btn-primary" href="{% url 'admin_custom:category_update' object.pk %}" role="button">Редактировать</a>
              <a class="btn btn-primary" href="{% url 'admin_custom:category_delete' object.pk %}" role="button">Удалить</a>
            </div>
          </div>
        </div>
      </div>


      {% comment %} <div class="category_record">
        <div class="category_name">
          {{ object.name|title }}
        </div>
        <div class="category_actions">
          <button>
            <a href={% url 'admin_custom:products' object.pk %}>
              товары категории
            </a>
          </button>
          <button>
            <a href={% url 'admin_custom:category_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin_custom:category_delete' object.pk %}>
              удалить
            </a>
          </button>
        </div>
        <div class="category_desc">
          {{ object.description|title }}
        </div>
      </div> {% endcomment %}
    {% endfor%}
    </div>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_update.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin_custom:categories' %}">
      к списку категорий
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_update.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin_custom:products' pk %}">
      к списку товаров
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="products_list">
    <button class="new_product">
      <a href={% url 'admin_custom:product_create' category.pk %}>
        новый продукт
      </a>
    </button>
        {{ category.name }}
    
    <div class="row mt-5">
    {% for object in object_list %}
    
      <div class="card mx-2 mb-3" style="max-width: 540px">
        <div class="row no-gutters">
          <div class="col-md-4 ">
            <img src="/media/{{object.image|default:'products_images/default.jpg'}}" class="card-img" alt="{{ object.name }}">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{ object.name|title }}</h5>
              <p class="card-text">{{ object.short_desc|title }}</p>
              {% comment %} <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> {% endcomment %}
              <a class="btn btn-primary" href="{% url 'admin_custom:product_update' object.pk %}" role="button">Редактировать</a>
              <a class="btn btn-primary" href="{% url 'admin_custom:product_delete' object.pk %}" role="button">Удалить</a>
            </div>
          </div>
        </div>
      </div>

      {% comment %} <div class="product_record">
        <img 
          src="/media/{{object.image|default:'products_images/default.jpg'}}"
          alt="{{ object.name }}"
          width="100 px">
        <div class="product_name">
          {{ object.name|title }}
        </div>
        <div class="product_actions">
          <button>
            <a href={% url 'admin_custom:product_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin_custom:product_delete' object.pk %}>
              удалить
            </a>
          </button>
        </div>
        <div class="summary">
          <b>цена</b>
          <p>{{ object.price }} руб</p>
          <b>количество</b>
          <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
          {{ object.short_desc|title }}
        </div>
        <br>
      </div> {% endcomment %}
    {% endfor%}
    </div>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin_custom:users' %}">
      к списку пользователей
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="users_list">
    <button class="new_user">
      <a href={% url 'admin_custom:user_create' %}>
        новый пользователь
      </a>
    </button>
    <div class="row mt-5">
      {% for object in object_list %}

        <div class="card mx-2 mb-3 {% if not object.is_active %} bg-light text-muted {% endif %}" style="width: 700px;">
          <div class="row no-gutters">
            <div class="col-md-4 ">
              <img src="/media/{{ object.avatar|default:'users_avatars/default.png' }}" class="card-img" alt="{{ object.name }}">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{ object.username }}</h5>
                <p class="card-text">{% if object.is_superuser %}
                    администратор
                  {% else %}
                    пользователь
                  {% endif %}</p>
                <p class="card-text">email: {{ object.email }}</p>
                <p class="card-text">age: {{ object.age }} лет</p>
                <p class="card-text">{% if object.first_name %}
                <b>{{ object.first_name|title }}
                    {% if object.last_name %}
                      {{ object.last_name|title }}
                    {% endif %}
                {% endif %}</b></p>
                <p class="card-text"><small class="text-muted">last_login: {{ object.last_login }}</small></p>
                <a class="btn btn-primary" href="{% url 'admin_custom:user_update' object.pk %}" role="button">Редактировать</a>
                <a class="btn btn-primary" href="{% url 'admin_custom:user_delete' object.pk %}" role="button">Удалить</a>
              </div>
            </div>
          </div>
        </div>

{% comment %}         <div 
        class="user_record {% if not object.is_active %}not_active{% endif %}">
          <img 
            src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}"
            alt="{{ object.username }}">
          <div class="user_role">
            {% if object.is_superuser %}
              администратор
            {% else %}
              пользователь
            {% endif %}
            <button>
              <a href={% url 'admin_custom:user_update' object.pk %}>
                редактировать
              </a>
            </button>
            <button>
              <a href={% url 'admin_custom:user_delete' object.pk %}>
                удалить
              </a>
            </button>
          </div>
          <div class="user_name">
            <p><strong>{{ object.username }}</strong></p>
          <p>
              {% if object.first_name %}
                <b>{{ object.first_name|title }}</b>
                  {% if object.last_name %}
                    <p>{{ object.last_name|title }}</p>
                  {% endif %}
              {% endif %}
            </p>
          </div>
          <div class="user_age">
            age:<br>
            {{ object.age }} лет
              </div>
          <div class="user_email">
            email:<br>
            {{ object.email }}
          </div>
          <div class="user_lastlogin">
            logged:<br>
            {{ object.last_login }}
          </div>
        </div> {% endcomment %}
      {% endfor%}
    </div>
  </div>
{% endblock %}