geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
]     

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.urls import path
from django.contrib import admin
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

if settings.DEBUG:
    import debug_toolbar


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', admin.site.urls),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('social/', include('social_django.urls', namespace='social')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   path('', mainapp.products, name='index'),
   path('category/<int:pk>/', mainapp.products, name='category'),
   path('product/<int:pk>/', mainapp.product, name='product'),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='Описание', blank=True)
    image = models.ImageField(upload_to='category_images', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

geekshop/mainapp/views.py
from django.shortcuts import render
from .models import ProductCategory, Product
from django.shortcuts import get_object_or_404
from basketapp.models import Basket
import random


main_links_menu = [
        {'href': 'main', 'name': 'Главная'},
        {'href': 'products:index', 'name': 'Продукты'},
        {'href': 'contact', 'name': 'Контакты'}
    ]


def get_basket_sum(request):
    basket = []
    if request.user.is_authenticated:
        basket = request.user.basket.all()
    total = 0
    for product in basket:
        position = get_object_or_404(Product, pk=product.pk)
        total = total + position.price * product.quantity
    return total


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]

    
def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).\
                                    exclude(pk=hot_product.pk)[:3]

    return same_products

def main(request):
    title = 'Главная'
    basket = []
    if request.user.is_authenticated:
        basket = request.user.basket.all()
    content = {
            'title': title,
            'links_menu': main_links_menu,
            'basket': basket            
        }
    return render(request, 'mainapp/index.html', content)


def products(request, pk=None):
    title = 'Категории'
    categories = ProductCategory.objects.all()
    basket = []
    if request.user.is_authenticated:
        basket = request.user.basket.all()
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by('price')
            category = {'name': 'Все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')
        content = {
            'title': title,
            'links_menu': main_links_menu,
            'category': category,
            'products': products,
            'categories': categories,
            'basket': basket,
            'same_products': same_products,
            'hot_product': hot_product,
        }
        return render(request, 'mainapp/products.html', content)
    content = {
        'title': title, 
        'links_menu': main_links_menu, 
        'same_products': same_products,
        'categories': categories,
        'basket': basket,
        'same_products': same_products,
        'hot_product': hot_product,
    }
    print(categories)
    return render(request, 'mainapp/catalog.html', content)


def contact(request):
    title = 'Контакты'
    basket = []
    if request.user.is_authenticated:
        basket = request.user.basket.all()
    content = {
            'title': title,
            'links_menu': main_links_menu,
            'basket': basket
        }
    return render(request, 'mainapp/contacts.html', content)

def product(request, pk):
    title = 'продукты'
    content = {
        'title': title,
        'links_menu': main_links_menu,
        'product_links_menu': ProductCategory.objects.all(), 
        'product': get_object_or_404(Product, pk=pk), 
        'basket': get_basket(request.user),
    }
    
    return render(request, 'mainapp/product.html', content)

geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
    <div class="container">
        {% block menu %}
        {% include 'mainapp/includes/inc_menu.html' %}
        {% endblock %}
        {% block content %}
        {% endblock %}

        {% block footer %}
        <div class="footer">
            <footer class="footer-copyright">&copy; Все права защищены</footer>
        </div>
        {% endblock %}
    </div>
</body>
</html>

geekshop/mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
<h1>{{ title }}</h1>
<div class="catalog">
    {% for category in categories %}
        <div class="block">
            <a href="{% url 'products:category' category.id %}"><img src="/media/{{ category.image }}" alt="{{ category.name }}" width="100"></a>
            <a href="{% url 'products:category' category.id %}" class="caption">подробнее</a>
        </div>
    {% endfor %}
</div>
<br>
<div class="description">
        <h3 class="big-bold">{{ hot_product.name }}</h3>
        <h3 class="red">горячее предложение</h3>
        <p class="price">{{ hot_product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
          заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ hot_product.description }} 
        </div>
</div>

{% endblock %}

geekshop/mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}

{% block title %}
    Контакты
{% endblock %}

{% block content %}
<h1>Напишите нам</h1>
<form action="">
    <fieldset>
        <input class="input-form" type="text" placeholder="Name"><br>
        <input class="input-form input-email" type="email" placeholder="ivan@mail.ru"><br>
        <input class="input-form" type="text" placeholder="Тема письма"><br>
        <textarea class="form-send-text" placeholder="Введите сюда ваше сообщение"></textarea><br>
        <button type="submit">Отправить</button>
    </fieldset>
</form>
<h1>Адрес</h1>
Телефон: 8-800-555-3535<br>
Адрес: г. Москва, улица Земляной Вал, 33<br>
Email: bezotveta@yandex.ru<br>
<iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A3da103d44204cf9426df5ef207a575dd0d8c3e2718788ccf89bb9b549ceb582d&amp;source=constructor" width="100%" height="374px" frameborder="0"></iframe>
{%  endblock %}

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{% block title %}
    Главная
{% endblock %}

{% block content %}
    <h1>IT Trade</h1>
    <p>Мы занимаемся компьютерной и офисной техникой, а также мини-АТС более 25 лет, с 1992 года. За это время мы зарекомендовали себя как надежного партнера, строго выполняющего свои обязательства! </p>
{% endblock %}

geekshop/mainapp/templates/mainapp/page1.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
    Процессор Intel Core i5-8600K OEM
{% endblock %}

{% block content %}
            <h1>Процессор Intel Core i5-8600K OEM</h1>
            <h2 class="head-description">Описание товара</h2>
            <div class="product-description">
                <a href="{%  static 'img/0513732_2.jpg' %}" target="_blank"><img class="image-description" src="{%  static 'img/0513732_2.jpg' %}"></a>
                <p class="short-description description-paragraph">Socket 1151 v2, 6-ядерный, 3200 МГц, Turbo: 4600 МГц, Coffee Lake-S, Кэш L2 - 1.5 Мб, Кэш L3 - 12 Мб, Intel UHD Graphics 630, 14 нм, 65 Вт</p>
            </div>
            <h2 class="head-description">Цена</h2>
            <div class="price">
                <p class="description-paragraph price-count"><b>22 000 руб</b></p>
                <button type="button" class="button_buy">Купить</button>
            </div>
            <h2 class="head-description">Характеристики товара</h2>
            <table class="description-table">
                <tbody>
                <tr>
                    <td>Производитель</td>
                    <td>Intel логотип Intel</td>
                </tr>
                <tr>
                    <td>Код производителя</td>
                    <td>CM8068403358316</td>
                </tr>
                <tr>
                    <td>Линейка</td>
                    <td>Core i7</td>
                </tr>
                <tr>
                    <td>Модель</td>
                    <td>8700</td>
                </tr>
                <tr>
                    <td>Socket</td>
                    <td>1151 v2</td>
                </tr>
                <tr>
                    <td>Ядро</td>
                    <td>Coffee Lake-S</td>
                </tr>
                <tr>
                    <td>Количество ядер</td>
                    <td>&nbsp;6</td>
                </tr>
                <tr>
                    <td>Частота поддерживаемой памяти</td>
                    <td>pc - 21300 (2667 МГц)</td>
                </tr>
                <tr>
                    <td>Технологии, команды и инструкции</td>
                    <td>MMX / SSE / SSE2 / SSE3 / SSSE3 / SSE4 / AES / AVX / AVX2 / BMI / BMI1 + BMI2<br>F16C / FMA3 / EM64T / NX / XD / VT-x / TBT 2.0 / MPX / SGX</td>
                </tr>
                <tr>
                    <td>Тепловыделение (TDP)</td>
                    <td>95 Вт</td>
                </tr>
                <tr>
                    <td>Тип упаковки</td>
                    <td>Oem</td>
                </tr>
                <tr>
                    <td>Дополнительно</td>
                    <td>Поддержка памяти Intel&reg; Optane&trade;</td>
                </tr>
                <tr>
                    <td>Разблокированный множитель</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>Комплект поставки</td>
                    <td>Процессор</td>
                </tr>
                <tr>
                    <td>Размеры (Д х Ш х В)</td>
                    <td>37.5 мм х 37.5 мм х</td>
                </tr>
                <tr>
                    <td>Размеры упаковки</td>
                    <td>50 x 50 x 100 мм</td>
                </tr>
                <tr>
                    <td>Вес в упаковке</td>
                    <td>0.05 кг</td>
                </tr>
                <tr>
                    <td>Сайт производителя</td>
                    <td>www.intel.ru</td>
                </tr>
                <tbody>
            </table>
            <h2 class="head-description">Подробное описание товара</h2>
            <p class="full-description description-paragraph">Intel Core i5-8600K - шустрый шестиядерный процессор, который послужит отличной основой при создании мощной мультимедийной станции.</p>
            <p class="full-description description-paragraph">Множитель в данной модели разблокирован, что дает хороший простор для разгона. Если же вы не слишком хорошо разбираетесь в подобных вещах, то можете немного повысить производительность путем активации Turbo-режима.</p>                
            <p class="full-description description-paragraph">Процессор поддерживает широкий спектр фирменных технологий вроде Enhanced Intel Speedstep Technology и Enhanced Virus Protection.</p>                
            <p class="full-description description-paragraph">Приятным бонусом служит и встроенное графическое ядро, возможностей которого вполне хватит для выполнения базовых задач и запуска несложных с графической точки зрения игр.</p>
{%  endblock %}

geekshop/mainapp/templates/mainapp/page2.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
    Сервер Dell PowerEdge T30
{% endblock %}

{% block content %}
    <h1>Сервер Dell PowerEdge T30</h1>
    <h2 class="head-description">Описание товара</h2>
    <div class="product-description">
        <a href="{%  static 'img/0535934_1.jpg' %}" target="_blank"><img class="image-description" src="{%  static 'img/0535934_1.jpg' %}"></a>
        <p class="short-description description-paragraph">Сервер Dell PowerEdge T30 E3-1225v5, 8GB DDR4, 2x250GB SSD SATA +1TB SATA 7.2k HDD, Intel RSC, DVDRW, 1GbE, AMT11, Tower, 1Y NBD</p>
    </div>
    <h2 class="head-description">Цена</h2>
    <div class="price">
        <p class="description-paragraph price-count"><b>58 890 руб</b></p>
        <button type="button" class="button_buy">Купить</button>
    </div>
    <h2 class="head-description">Характеристики товара</h2>
    <table class="description-table">
        <tbody>
            <tr>
                <td>Тип оборудования</span></td>
                <td>Сервер</span></td>
            </tr>
            <tr>
                <td>Процессор</span></td>
                <td>Intel Xeon E3-1225v5 (SkyLake, 3.3 ГГц, 8Мб, S1151)</span></td>
            </tr>
            <tr>
                <td>Чипсет</span></td>
                <td>Intel C236</span></td>
            </tr>
            <tr>
                <td>Оперативная память</span></td>
                <td>8 ГБ DDR4 2133МГц ECC</span></td>
            </tr>
            <tr>
                <td>Жесткий диск</span></td>
                <td>2 x 250Гб SSD SATA III</span></td>
            </tr>
            <tr>
                <td>Видеокарта</span></td>
                <td>Matrox G200eW (16 Мб)</span></td>
            </tr>
            <tr>
                <td>Оптические накопители</span></td>
                <td>DVD±RW Super Multi</span></td>
            </tr>
            <tr>
                <td>Тип корпуса</span></td>
                <td>Mini Tower</span></td>
            </tr>
            <tr>
                <td>Сетевая карта</span></td>
                <td>1 x 10/100/1000 Мбит/с</span></td>
            </tr>
            <tr>
                <td>Операционная система</span></td>
                <td>Не установлена</span></td>
            </tr>
            <tr>
                <td>Тип упаковки</span></td>
                <td>Retail</span></td>
            </tr>
            <tr>
                <td>Комплект поставки</span></td>
                <td>Сервер</span></td>
            </tr>
            <tr>
                <td>Размеры упаковки</span></td>
                <td>270 x 560 x 470 мм</span></td>
            </tr>
            <tr>
                <td>Вес в упаковке</span></td>
                <td>12 кг</span></td>
            </tr>
            <tr>
                <td>Сайт производителя</span></td>
                <td>www.dell.com</span></td>
            </tr>
        <tbody>
    </table>
    <h2 class="head-description">Подробное описание товара</h2>
    <p class="full-description description-paragraph">Dell PowerEdge T30 E3-1225v5 (3.3GHz) 4C, 8GB (1x8GB) 2133MHz DDR4 UDIMM, (2)x 250GB SSD SATA 3D-NAND TLC 2.5" Drive + 1TB SATA 7200 rpm Cabled 3.5" HDD (up to 4x3.5"), Onboard SATA RAID (Intel Rapid Storage Controller 12.X), DVD+/-RW, Intel i219 Single Port 1GbE, AMT 11.0, PS 290W (fixed), Tower, 1Y NBD</p>
{% endblock %}

geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
      <div class="details-slider">
        <div class="slider-control">
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 1" width="100px">
            </a>
          </div>
        </div>
      </div>

      <div class="description">
        <h3 class="big-bold">{{ product.name }}</h3>
        <br>
        <p class="price"> {{ product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' product.pk %}" class="red-button">
          заказать 
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ product.description }}
        </div>
      </div>
    </div>

  </div>

  <div class="clr"></div>
  {% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
<h1>{{ category.name }}</h1>
{% include 'mainapp/includes/inc_categories_menu.html' %}
<div class="catalog">
    <div class="category-products clearfix">
        {% for product in products %}
            <div class="product-block">
            <a href="{% url 'products:product' product.pk %}">
                <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}", width="100">
                <div class="text">
                {% comment %} <img src="{% static 'img/icon-hover.png' %}" alt="hover"> {% endcomment %}
                <h4>{{ product.name }}</h4>
                <p>{{ product.description }} </p>
                </div>
            </a>
            </div>
        {% endfor %}
    </div> 
</div>
{% endblock %}